#pragma once
//ÉwÉbÉ_Å[ÇÕÇ±Ç±Ç…Ç‹Ç∆ÇﬂÇÈbyÇÕÇ‚Çµ
//#include "../Maptip/Map.h"
#include "Maptip/Map.h"
#include"Base/Base.h"
#include"Player/Player.h"
#include"Enemy/Enemy.h"
#include"Player/kamano.h"
#include"Player/hayashi.h"
#include"Player/itihara.h"
#include"Maptip/Wall.h"
#include"Maptip/Dorup.h"
#include"Maptip/Dordown.h"
#include"Maptip/Wallhed.h"
#include "UI/AnimData.h"
#include "UI/Field.h"
#include "UI/Slash.h"
#include "UI/Effect.h"
#include"Enemy/EnemyManager.h"
#include"Enemy/trapbullet.h"
#include"UI/Gameover.h"
/*#include "../UI/AnimData.h"
#include "../UI/Field.h"
#include "../UI/Slash.h"
#include "../UI/Effect.h"
#include "../Player/Player.h"
#include "../Enemy/Enemy.h"
#include "../UI/Goal.h"
#include "../UI/Title.h"
#include"../Enemy/kaiga.h"
#include "../Game/Text.h"*/
#include "Player/Player.h"
#include "Enemy/Enemy.h"
#include "UI/Goal.h"
#include "UI/Title.h"
#include"Enemy/kaiga.h"
#include "Game/Text.h"
#include"Game/SaveLoad.h"
#include"Game/Select.h"
#include"Maptip/hondana.h"
